  steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', './API','--no-cache','-t','gcr.io/all-services-project/$_SERVICE_NAME:$COMMIT_SHA']
    id: 'Build'
    timeout: 300s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/all-services-project/$_SERVICE_NAME:$COMMIT_SHA']
    id: 'Push'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'update','$_SERVICE_NAME', '--platform=managed','--image=gcr.io/all-services-project/$_SERVICE_NAME:$COMMIT_SHA','--labels=managed-by=gcp-cloud-build-deploy-cloud-run', '--region=us-east1','--quiet']
    id: 'Deploy'