name: 
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: model_status
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          TYPE: ${{ secrets.TYPE }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AUTH_URI: ${{ secrets.AUTH_URI }}
          TOKEN_URI: ${{ secrets.TOKEN_URI }}
          AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
          CLIENT_x509_CERT_URL: ${{ secrets.CLIENT_x509_CERT_URL }}
        run: |
          pip install -r src/actions_requirements.txt
          python src/study_case_1_plot.py
          python src/study_case_2_plot.py
          
          echo "## Covid-19 impact report" > report.md
          echo "### Covid-19 interest over time and Covid-19 interest vs Online courses interest" >> report.md     
          cml-publish impact.png --md >> report.md
          
          echo "## Covid-19 status over time model" >> report.md
          cat text.txt >> report.md
          cml-publish prediction.png --md >> report.md
          
          cml-send-comment report.md
